export enum SettingValueType {
    STRING = "String",
    BOOLEAN = "Boolean",
    NUMBER = "Number",
}

export enum PeriodOfTime {
    MORNING = "Morning",
    AFTERNOON = "Afternoon",
}

export enum SettingKey {
    MORNING_WORK_FROM = "MORNING_WORK_FROM",
    MORNING_WORK_TO = "MORNING_WORK_TO",
    AFTERNOON_WORK_FROM = "AFTERNOON_WORK_FROM",
    AFTERNOON_WORK_TO = "AFTERNOON_WORK_TO",
    ATTENDANCE_REGISTER_DELAY_ALLOW = "ATTENDANCE_REGISTER_DELAY_ALLOW",
    ATTENDANCE_PRIVATE_KEY = "ATTENDANCE_PRIVATE_KEY",
    WORKSPACE_BSSID = "WORKSPACE_BSSID",
    WORKSPACE_IP_ADDRESS = "WORKSPACE_IP_ADDRESS",
}