# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:
    name: build and public
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: npm install
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
          
#     - name: npm test
#       uses: actions/npm@master
#       with:
#           args: run test
    - name: Test the Testcases 
      run: |
        npm install
        npm run build --if-present
#        npm test
    - name: Login to Docker Hub
      run: docker login --username "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"
    - name: Build the Docker Image 
      run: docker build . --file Dockerfile --tag hoang1712/nodejs-docker-cnpm
    - name: Push the Docker Image 
      run: docker push hoang1712/nodejs-docker-cnpm
      
      env:
        CI: true
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
          password: ${{ secrets.REMOTE_PASSWORD }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          script: |
            cd /home/hoang171220001/diem-danh-cnpm
            git pull origin main
            npm run build && pm2 restart main
#           EXCLUDE: "/dist/, /node_modules/"
      
#     - name: docker build
#       uses: actions/docker/cli@master
#       with:
#         args: build -t hoang1712/nodejs-docker-cnpm .
#     - name: docker login
#       uses: actions/docker/login@master
#       env:
#         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#     - name: docker push
#       uses: actions/docker/cli@master
#       with:
#         args: push hoang1712/nodejs-docker-cnpm
